aliases:
  dp: deployments
  sec: v1/secrets
  jo: jobs
  cr: clusterroles
  crb: clusterrolebindings
  ro: roles
  rb: rolebindings
  np: networkpolicies
  spot: nodes karpenter.sh/capacity-type=spot
  ondemand: nodes karpenter.sh/capacity-type=on-demand
  karpenter: nodes karpenter.sh/nodepool
