aliases:
  dp: deployments
  sec: v1/secrets
  jo: jobs
  cr: clusterroles
  crb: clusterrolebindings
  ro: roles
  rb: rolebindings
  np: networkpolicies
  spot: nodes karpenter.sh/capacity-type=spot
  ondemand: nodes karpenter.sh/capacity-type=on-demand
  karpenter: nodes karpenter.sh/registered=true
  np-default: nodes karpenter.sh/nodepool=default
  np-default-arm64: nodes karpenter.sh/nodepool=default-arm64
  np-dba: nodes karpenter.sh/nodepool=dba
  np-cronjob: nodes karpenter.sh/nodepool=cronjob
  np-gitlab-runner: nodes karpenter.sh/nodepool=gitlab-runner
