views:
  v1/pods:
    # sortColumn: RESTARTS:desc   # Optional: set the default sort column
    columns:
      - STATUS

  v1/nodes:
    sortColumn: AGE:desc,NODEPOOL:desc,NAME:desc
    columns:
      - NAME
      - STATUS
      - AGE
      - NODEPOOL:.metadata.labels.karpenter\.sh/nodepool
      - CAPACITY-TYPE:.metadata.labels.karpenter\.sh/capacity-type
      - INSTANCE-TYPE:.metadata.labels.node\.kubernetes\.io/instance-type
      - ZONE:.metadata.labels.topology\.kubernetes\.io/zone
      - CPU:.metadata.labels.karpenter\.k8s\.aws/instance-cpu
      - MEMORY:.metadata.labels.karpenter\.k8s\.aws/instance-memory
